name: Docker Image CI
env:
  REGISTRY: ghcr.io
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  info:
    runs-on: ubuntu-latest
    name: Get repository information
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: elraro/free-asterisk-arm
          fetch-depth: 0
          token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    name: Build image
    needs: [info]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3.2.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm/v8
          tags: latest
          labels: latest
